/*
 * KEY POINTS AND READING TIME — the two deterministic derivations the Blog post page renders.
 *
 * ══ WHY "KEY POINTS", NOT "AI SUMMARY" (`FD-DAT-20`) ══
 *
 * The founder asked for an "AI summary at the top". What ships is a DETERMINISTIC DERIVATION: the bullets are
 * extracted from the post's own paragraphs by a fixed rule, with no reader request, no prompt, no provider, no
 * model inference, no tokens and no cost. `FD-DAT-20` rules that *"deterministic generation must not be
 * described as AI"* — in BOTH directions: claiming AI would misdescribe a calculation, and disclaiming AI would
 * raise the idea in a surface where it does not arise. So the block is labelled **"Key points"**, carries a
 * positive statement of provenance ("drawn from the article below"), and never mentions AI at all.
 *
 * If a model ever writes this summary instead, the surface moves under `FD-DAT-02` gating with `FD-DAT-12`
 * usage recording — the ruling attaches to what the surface DOES (see `FUTURE_BLOG_API.keyPoints`).
 *
 * ══ THE RULE ══
 *
 * One bullet per body section, in body order: the FIRST SENTENCE of the section's first paragraph. The corpus
 * is written so those sentences stand alone (a discipline the BFF enforces structurally: a lead plus at least
 * two headed sections). Capped at five bullets; the BFF's three-section minimum guarantees at least three. The
 * same input always produces the same output, which is what makes the block testably DERIVED rather than
 * free-authored.
 */

import type { BlogPostRecord } from "./blogContract";

/** The visible label. Never "AI", never "summary generated by" anything (`FD-DAT-20`). */
export const KEY_POINTS_LABEL = "Key points";

/** The provenance sentence rendered under the label — positive, and silent about AI in both directions. */
export const KEY_POINTS_PROVENANCE = "Drawn from the article below.";

export const KEY_POINTS_MAX = 5;
export const KEY_POINTS_MIN = 3;

/**
 * The first sentence of a paragraph. Sentence end = `.`, `!` or `?` followed by whitespace; a paragraph with no
 * such boundary IS one sentence. Deliberately simple and fixed — a cleverer splitter that changed over time
 * would silently rewrite published Key points.
 */
export function firstSentence(paragraph: string): string {
  const match = paragraph.match(/^[\s\S]*?[.!?](?=\s)/);
  return (match ? match[0] : paragraph).trim();
}

/**
 * The derived Key points: one bullet per section, first sentence of the section's first paragraph, in order,
 * at most `KEY_POINTS_MAX`. Deterministic by construction.
 */
export function deriveKeyPoints(post: BlogPostRecord): string[] {
  const points: string[] = [];
  for (const section of post.sections) {
    if (points.length >= KEY_POINTS_MAX) break;
    const lead = section.paragraphs[0];
    if (!lead) continue;
    points.push(firstSentence(lead));
  }
  return points;
}

/** Words-per-minute for the reading-time figure. A fixed constant, so the label cannot drift between builds. */
const WORDS_PER_MINUTE = 220;

/**
 * Reading time in whole minutes, floor 1 — arithmetic over the post's own word count, never an engagement
 * estimate. Rendered as "N min read".
 */
export function readingTimeMinutes(post: BlogPostRecord): number {
  const words = post.sections
    .flatMap((s) => [s.heading ?? "", ...s.paragraphs])
    .join(" ")
    .split(/\s+/)
    .filter((w) => w.length > 0).length;
  return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}

/**
 * The text the Listen control reads: headline, the Key points (announced with their label), then the body with
 * its section headings. Built server-side so the audio and the page always speak the same article.
 */
export function listenText(post: BlogPostRecord): string {
  const keyPoints = deriveKeyPoints(post);
  const body = post.sections.flatMap((s) => [...(s.heading ? [s.heading] : []), ...s.paragraphs]);
  return [post.headline, `${KEY_POINTS_LABEL}:`, ...keyPoints, ...body].join(" \n");
}
