/*
 * Feed-derived draw events for the representative preview States — LRG-STATE-047.
 *
 * PRODUCTION-DERIVED, TRANSCRIBED WITH PROVENANCE. Nothing here is authored, estimated or inferred.
 *
 * WHY THIS FILE IS SEPARATE FROM `floridaDrawEvents.ts`.
 * Florida's events were transcribed by LRG-STATE-025 against the operator's own published pages as well as
 * the feed, and Florida is the locked reference template. That module is therefore left untouched, and this
 * one carries the four additional lottery States. Both satisfy the same `StateDrawEvent` shape, and
 * `stateDrawEvents.ts` is the single lookup the model uses — so neither is special to the renderer.
 *
 * PROVENANCE
 *   [F1] 04-sample-data/source-xml/latest-results-lc.xml — the production results feed. Extracted
 *        2026-08-01. `gameId`, `gameName`, `result-date`, `numbers-str`, `next-date` and, for the two
 *        multi-state games, `prize`/`next-prize` are the feed's own values. `numbers-str` was split into
 *        main numbers, named special balls, multiplier and secondary draw; no value was altered.
 *   [F2] 04-sample-data/reference-tables/game.csv — production database export. `GAMETIME` supplies
 *        `drawTimeLocal` and `PLAY_TYPE` supplies `playType`.
 *
 * WHAT IS DELIBERATELY ABSENT, and why absence is the correct value.
 *   - `drawDays` is EMPTY for every event. Florida's draw days came from the operator's own published game
 *     pages, and no equivalent source for these four States exists in the repository. An empty string is the
 *     honest value; the schedule section suppresses rather than printing a guess.
 *   - `salesCutoff` is `null` for the same reason. `game.csv` `CUTOFFTIME` holds free-text notes rather than
 *     a governed cutoff time, so it is not transcribed as one.
 *   - `topPrizeDisplay` and `nextPrizeDisplay` are `null` for every STATE-NATIVE game. The feed carries a
 *     money value, but the governed prize SEMANTICS for these games are unverified — whether that figure is
 *     an annuitized jackpot, a cash value or a fixed top prize is exactly what `PrizeSpec` exists to record.
 *     Printing an unlabelled money figure is the defect `resultFormatContract.ts` was written to prevent.
 *     Powerball and Mega Millions keep theirs: their formats are `verifiedOfficial` and shared with Florida.
 *   - CALIFORNIA MEGA MILLIONS HAS NO NUMBERS. The feed carries `<numbers-str date="07/07/2026"/>` — a
 *     genuinely empty element — with a result date and a prize but no drawn values. It is transcribed
 *     faithfully as an empty draw, and the presentation layer suppresses the member rather than borrowing
 *     the identical Mega Millions result that the Michigan, Virginia and Maryland blocks do carry. That is
 *     `FAM-04`, exercised by real production data rather than by a manufactured case.
 *   - Michigan Keno (402), Michigan Poker Lotto (403) and California Daily Derby (315) are ABSENT. Their
 *     formats are not determined by repository evidence — see `stateFormatRegistry.ts` for each reason.
 *     A game whose result shape we cannot verify is not rendered at all.
 */

import type { StateDrawEvent } from "./stateDrawEvents";

/** Michigan — 8 transcribed draw events [F1] + [F2]. */
export const MI_DRAW_EVENTS: readonly StateDrawEvent[] = [
  {
    gameId: 1012, formatId: 1012,
    familyKey: "powerball", familyName: "Powerball",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Powerball",
    drawDays: "", drawTimeLocal: "10:59 PM",
    salesCutoff: null, playType: "5/69+1/26",
    resultDate: "2026-07-08",
    mainNumbers: [12, 29, 37, 43, 55],
    specialBalls: [{ label: "Powerball", values: [18] }],
    multiplier: { label: "Power Play", value: 4 },
    secondaryDraw: { label: "Double Play", mainNumbers: [6, 27, 33, 44, 69], specialBalls: [{ label: "Powerball", values: [23] }] },
    topPrizeDisplay: "$435,000,000",
    nextDrawDate: "2026-07-11", nextPrizeDisplay: "$457,000,000",
    feedUpdatedRaw: "Thu 07/09/2026 12:11:54 AM EDT",
  },
  {
    gameId: 1013, formatId: 1013,
    familyKey: "mega-millions", familyName: "Mega Millions",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Mega Millions",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5/70+1/24",
    resultDate: "2026-07-07",
    mainNumbers: [2, 31, 35, 36, 63],
    specialBalls: [{ label: "Mega Ball", values: [12] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: "$576,000,000",
    nextDrawDate: "2026-07-10", nextPrizeDisplay: "$604,000,000",
    feedUpdatedRaw: "Tue 07/07/2026 11:23:57 PM EDT",
  },
  {
    gameId: 517, formatId: 517,
    familyKey: "classic-lotto-47", familyName: "Classic Lotto 47",
    gameClass: "stateJackpot", drawPeriod: null,
    feedName: "Michigan-Classic Lotto 47",
    drawDays: "", drawTimeLocal: "7:29 PM",
    salesCutoff: null, playType: "6/47",
    resultDate: "2026-07-08",
    mainNumbers: [12, 15, 20, 30, 37, 39],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: { label: "Double Play", mainNumbers: [1, 17, 18, 28, 31, 38], specialBalls: [] },
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-11", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 09:29:12 PM EDT",
  },
  {
    gameId: 401, formatId: 401,
    familyKey: "fantasy-5", familyName: "Fantasy 5",
    gameClass: "stateDaily", drawPeriod: null,
    feedName: "Michigan-Fantasy 5",
    drawDays: "", drawTimeLocal: "7:29 PM",
    salesCutoff: null, playType: "5/39",
    resultDate: "2026-07-08",
    mainNumbers: [6, 7, 9, 13, 17],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: { label: "Double Play", mainNumbers: [18, 25, 28, 32, 39], specialBalls: [] },
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:16:50 PM EDT",
  },
  {
    gameId: 397, formatId: 397,
    familyKey: "daily-3", familyName: "Daily 3",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "Michigan-Daily 3 Midday",
    drawDays: "", drawTimeLocal: "12:59 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-09",
    mainNumbers: [7, 0, 2],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 01:16:35 PM EDT",
  },
  {
    gameId: 398, formatId: 398,
    familyKey: "daily-3", familyName: "Daily 3",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "Michigan-Daily 3 Evening",
    drawDays: "", drawTimeLocal: "7:29 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [6, 6, 6],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:37 PM EDT",
  },
  {
    gameId: 399, formatId: 399,
    familyKey: "daily-4", familyName: "Daily 4",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "Michigan-Daily 4 Midday",
    drawDays: "", drawTimeLocal: "12:59 PM",
    salesCutoff: null, playType: "4-Digits",
    resultDate: "2026-07-09",
    mainNumbers: [2, 0, 2, 0],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 01:16:35 PM EDT",
  },
  {
    gameId: 400, formatId: 400,
    familyKey: "daily-4", familyName: "Daily 4",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "Michigan-Daily 4 Evening",
    drawDays: "", drawTimeLocal: "7:29 PM",
    salesCutoff: null, playType: "4-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [6, 9, 1, 7],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:37 PM EDT",
  },
];

/** Virginia — 15 transcribed draw events [F1] + [F2]. */
export const VA_DRAW_EVENTS: readonly StateDrawEvent[] = [
  {
    gameId: 1012, formatId: 1012,
    familyKey: "powerball", familyName: "Powerball",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Powerball",
    drawDays: "", drawTimeLocal: "10:59 PM",
    salesCutoff: null, playType: "5/69+1/26",
    resultDate: "2026-07-08",
    mainNumbers: [12, 29, 37, 43, 55],
    specialBalls: [{ label: "Powerball", values: [18] }],
    multiplier: { label: "Power Play", value: 4 },
    secondaryDraw: null,
    topPrizeDisplay: "$435,000,000",
    nextDrawDate: "2026-07-11", nextPrizeDisplay: "$457,000,000",
    feedUpdatedRaw: "Thu 07/09/2026 12:11:54 AM EDT",
  },
  {
    gameId: 1013, formatId: 1013,
    familyKey: "mega-millions", familyName: "Mega Millions",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Mega Millions",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5/70+1/24",
    resultDate: "2026-07-07",
    mainNumbers: [2, 31, 35, 36, 63],
    specialBalls: [{ label: "Mega Ball", values: [12] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: "$576,000,000",
    nextDrawDate: "2026-07-10", nextPrizeDisplay: "$604,000,000",
    feedUpdatedRaw: "Tue 07/07/2026 11:23:57 PM EDT",
  },
  {
    gameId: 574, formatId: 574,
    familyKey: "bank-a-million", familyName: "Bank a Million",
    gameClass: "stateJackpot", drawPeriod: null,
    feedName: "Virginia-Bank a Million",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "6/40",
    resultDate: "2026-07-08",
    mainNumbers: [1, 2, 14, 26, 36, 37],
    specialBalls: [{ label: "Bonus", values: [8] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-11", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:32:27 PM EDT",
  },
  {
    gameId: 542, formatId: 542,
    familyKey: "cash-5", familyName: "Cash 5",
    gameClass: "stateDaily", drawPeriod: null,
    feedName: "Virginia-Cash 5 Night",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5/45",
    resultDate: "2026-07-08",
    mainNumbers: [2, 5, 16, 23, 45],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 01:41:22 AM EDT",
  },
  {
    gameId: 488, formatId: 488,
    familyKey: "pick-3", familyName: "Pick 3",
    gameClass: "dailyNumbers", drawPeriod: "Day",
    feedName: "Virginia-Pick 3 Day",
    drawDays: "", drawTimeLocal: "2:00 PM",
    salesCutoff: null, playType: "3-Digits+1",
    resultDate: "2026-07-09",
    mainNumbers: [7, 5, 4],
    specialBalls: [{ label: "Fireball", values: [9] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 02:16:46 PM EDT",
  },
  {
    gameId: 489, formatId: 489,
    familyKey: "pick-3", familyName: "Pick 3",
    gameClass: "dailyNumbers", drawPeriod: "Night",
    feedName: "Virginia-Pick 3 Night",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "3-Digits+1",
    resultDate: "2026-07-08",
    mainNumbers: [4, 7, 4],
    specialBalls: [{ label: "Fireball", values: [3] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:32:16 PM EDT",
  },
  {
    gameId: 490, formatId: 490,
    familyKey: "pick-4", familyName: "Pick 4",
    gameClass: "dailyNumbers", drawPeriod: "Day",
    feedName: "Virginia-Pick 4 Day",
    drawDays: "", drawTimeLocal: "2:00 PM",
    salesCutoff: null, playType: "4-Digits+1",
    resultDate: "2026-07-09",
    mainNumbers: [6, 3, 8, 4],
    specialBalls: [{ label: "Fireball", values: [4] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 02:16:47 PM EDT",
  },
  {
    gameId: 491, formatId: 491,
    familyKey: "pick-4", familyName: "Pick 4",
    gameClass: "dailyNumbers", drawPeriod: "Night",
    feedName: "Virginia-Pick 4 Night",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "4-Digits+1",
    resultDate: "2026-07-08",
    mainNumbers: [9, 4, 3, 6],
    specialBalls: [{ label: "Fireball", values: [6] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:32:17 PM EDT",
  },
  {
    gameId: 641, formatId: 641,
    familyKey: "pick-5", familyName: "Pick 5",
    gameClass: "dailyNumbers", drawPeriod: "Day",
    feedName: "Virginia-Pick 5 Day",
    drawDays: "", drawTimeLocal: "1:59 PM",
    salesCutoff: null, playType: "5-Digits+1",
    resultDate: "2026-07-09",
    mainNumbers: [9, 8, 1, 5, 2],
    specialBalls: [{ label: "Fireball", values: [3] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 02:16:54 PM EDT",
  },
  {
    gameId: 642, formatId: 642,
    familyKey: "pick-5", familyName: "Pick 5",
    gameClass: "dailyNumbers", drawPeriod: "Night",
    feedName: "Virginia-Pick 5 Night",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5-Digits+1",
    resultDate: "2026-07-08",
    mainNumbers: [2, 8, 1, 8, 4],
    specialBalls: [{ label: "Fireball", values: [4] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:32:33 PM EDT",
  },
  {
    gameId: 631, formatId: 631,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "Coffee Break",
    feedName: "Virginia-Cash Pop Coffee Break",
    drawDays: "", drawTimeLocal: "09:00 AM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-09",
    mainNumbers: [4],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 09:16:43 AM EDT",
  },
  {
    gameId: 632, formatId: 632,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "Lunch Break",
    feedName: "Virginia-Cash Pop Lunch Break",
    drawDays: "", drawTimeLocal: "12:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-09",
    mainNumbers: [14],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 12:16:41 PM EDT",
  },
  {
    gameId: 633, formatId: 633,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "Rush Hour",
    feedName: "Virginia-Cash Pop Rush Hour",
    drawDays: "", drawTimeLocal: "05:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-08",
    mainNumbers: [8],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 05:16:43 PM EDT",
  },
  {
    gameId: 634, formatId: 634,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "Prime Time",
    feedName: "Virginia-Cash Pop Prime Time",
    drawDays: "", drawTimeLocal: "09:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-08",
    mainNumbers: [8],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 09:16:48 PM EDT",
  },
  {
    gameId: 635, formatId: 635,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "After Hours",
    feedName: "Virginia-Cash Pop After Hours",
    drawDays: "", drawTimeLocal: "11:59 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-08",
    mainNumbers: [11],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 12:16:55 AM EDT",
  },
];

/** California — 7 transcribed draw events [F1] + [F2]. */
export const CA_DRAW_EVENTS: readonly StateDrawEvent[] = [
  {
    gameId: 1012, formatId: 1012,
    familyKey: "powerball", familyName: "Powerball",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Powerball",
    drawDays: "", drawTimeLocal: "10:59 PM",
    salesCutoff: null, playType: "5/69+1/26",
    resultDate: "2026-07-08",
    mainNumbers: [12, 29, 37, 43, 55],
    specialBalls: [{ label: "Powerball", values: [18] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: "$435,000,000",
    nextDrawDate: "2026-07-11", nextPrizeDisplay: "$457,000,000",
    feedUpdatedRaw: "Thu 07/09/2026 12:11:54 AM EDT",
  },
  {
    gameId: 1013, formatId: 1013,
    familyKey: "mega-millions", familyName: "Mega Millions",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Mega Millions",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5/70+1/24",
    resultDate: "2026-07-07",
    mainNumbers: [],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: "$576,000,000",
    nextDrawDate: "2026-07-10", nextPrizeDisplay: "$604,000,000",
    feedUpdatedRaw: "Tue 07/07/2026 11:23:57 PM EDT",
  },
  {
    gameId: 316, formatId: 316,
    familyKey: "superlotto-plus", familyName: "SuperLotto Plus",
    gameClass: "stateJackpot", drawPeriod: null,
    feedName: "California-SuperLotto Plus",
    drawDays: "", drawTimeLocal: "7:57 PM",
    salesCutoff: null, playType: "5/47+1/27",
    resultDate: "2026-07-08",
    mainNumbers: [18, 22, 28, 33, 38],
    specialBalls: [{ label: "Mega Ball", values: [15] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-11", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:58:39 PM EDT",
  },
  {
    gameId: 314, formatId: 314,
    familyKey: "fantasy-5", familyName: "Fantasy 5",
    gameClass: "stateDaily", drawPeriod: null,
    feedName: "California-Fantasy 5",
    drawDays: "", drawTimeLocal: "6:30 PM",
    salesCutoff: null, playType: "5/39",
    resultDate: "2026-07-08",
    mainNumbers: [11, 23, 25, 28, 36],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 10:04:38 PM EDT",
  },
  {
    gameId: 311, formatId: 311,
    familyKey: "daily-3", familyName: "Daily 3",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "California-Daily 3 Midday",
    drawDays: "", drawTimeLocal: "1:00 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [1, 3, 1],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 04:16:36 PM EDT",
  },
  {
    gameId: 312, formatId: 312,
    familyKey: "daily-3", familyName: "Daily 3",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "California-Daily 3 Evening",
    drawDays: "", drawTimeLocal: "6:30 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [2, 2, 6],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 09:46:34 PM EDT",
  },
  {
    gameId: 313, formatId: 313,
    familyKey: "daily-4", familyName: "Daily 4",
    gameClass: "dailyNumbers", drawPeriod: null,
    feedName: "California-Daily 4",
    drawDays: "", drawTimeLocal: "6:30 PM",
    salesCutoff: null, playType: "4-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [3, 1, 3, 1],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 09:46:35 PM EDT",
  },
];

/** Maryland — 14 transcribed draw events [F1] + [F2]. */
export const MD_DRAW_EVENTS: readonly StateDrawEvent[] = [
  {
    gameId: 1012, formatId: 1012,
    familyKey: "powerball", familyName: "Powerball",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Powerball",
    drawDays: "", drawTimeLocal: "10:59 PM",
    salesCutoff: null, playType: "5/69+1/26",
    resultDate: "2026-07-08",
    mainNumbers: [12, 29, 37, 43, 55],
    specialBalls: [{ label: "Powerball", values: [18] }],
    multiplier: { label: "Power Play", value: 4 },
    secondaryDraw: { label: "Double Play", mainNumbers: [6, 27, 33, 44, 69], specialBalls: [{ label: "Powerball", values: [23] }] },
    topPrizeDisplay: "$435,000,000",
    nextDrawDate: "2026-07-11", nextPrizeDisplay: "$457,000,000",
    feedUpdatedRaw: "Thu 07/09/2026 12:11:54 AM EDT",
  },
  {
    gameId: 1013, formatId: 1013,
    familyKey: "mega-millions", familyName: "Mega Millions",
    gameClass: "multiState", drawPeriod: null,
    feedName: "Multi-State (US)-Mega Millions",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "5/70+1/24",
    resultDate: "2026-07-07",
    mainNumbers: [2, 31, 35, 36, 63],
    specialBalls: [{ label: "Mega Ball", values: [12] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: "$576,000,000",
    nextDrawDate: "2026-07-10", nextPrizeDisplay: "$604,000,000",
    feedUpdatedRaw: "Tue 07/07/2026 11:23:57 PM EDT",
  },
  {
    gameId: 515, formatId: 515,
    familyKey: "multi-match", familyName: "Multi Match",
    gameClass: "stateJackpot", drawPeriod: null,
    feedName: "Maryland-Multi Match",
    drawDays: "", drawTimeLocal: "11:07 PM",
    salesCutoff: null, playType: "6/43",
    resultDate: "2026-07-06",
    mainNumbers: [10, 11, 15, 17, 31, 34],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Mon 07/06/2026 11:23:07 PM EDT",
  },
  {
    gameId: 392, formatId: 392,
    familyKey: "bonus-match-5", familyName: "Bonus Match 5",
    gameClass: "stateDaily", drawPeriod: null,
    feedName: "Maryland-Bonus Match 5",
    drawDays: "", drawTimeLocal: "7:51 PM",
    salesCutoff: null, playType: "5/39",
    resultDate: "2026-07-08",
    mainNumbers: [17, 29, 35, 36, 38],
    specialBalls: [{ label: "Bonus", values: [4] }],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:36 PM EDT",
  },
  {
    gameId: 388, formatId: 388,
    familyKey: "pick-3", familyName: "Pick 3",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "Maryland-Pick 3 Midday",
    drawDays: "", drawTimeLocal: "12:28 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-09",
    mainNumbers: [4, 9, 7],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 12:46:39 PM EDT",
  },
  {
    gameId: 389, formatId: 389,
    familyKey: "pick-3", familyName: "Pick 3",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "Maryland-Pick 3 Evening",
    drawDays: "", drawTimeLocal: "7:56 PM",
    salesCutoff: null, playType: "3-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [9, 0, 5],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:34 PM EDT",
  },
  {
    gameId: 390, formatId: 390,
    familyKey: "pick-4", familyName: "Pick 4",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "Maryland-Pick 4 Midday",
    drawDays: "", drawTimeLocal: "12:28 PM",
    salesCutoff: null, playType: "4-Digits",
    resultDate: "2026-07-09",
    mainNumbers: [0, 5, 8, 7],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 12:46:40 PM EDT",
  },
  {
    gameId: 391, formatId: 391,
    familyKey: "pick-4", familyName: "Pick 4",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "Maryland-Pick 4 Evening",
    drawDays: "", drawTimeLocal: "7:56 PM",
    salesCutoff: null, playType: "4-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [4, 7, 6, 1],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:35 PM EDT",
  },
  {
    gameId: 629, formatId: 629,
    familyKey: "pick-5", familyName: "Pick 5",
    gameClass: "dailyNumbers", drawPeriod: "Midday",
    feedName: "Maryland-Pick 5 Midday",
    drawDays: "", drawTimeLocal: "12:28 PM",
    salesCutoff: null, playType: "5-Digits",
    resultDate: "2026-07-09",
    mainNumbers: [0, 3, 9, 6, 3],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 12:46:49 PM EDT",
  },
  {
    gameId: 630, formatId: 630,
    familyKey: "pick-5", familyName: "Pick 5",
    gameClass: "dailyNumbers", drawPeriod: "Evening",
    feedName: "Maryland-Pick 5 Evening",
    drawDays: "", drawTimeLocal: "07:56 PM",
    salesCutoff: null, playType: "5-Digits",
    resultDate: "2026-07-08",
    mainNumbers: [0, 0, 6, 4, 3],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 08:01:59 PM EDT",
  },
  {
    gameId: 654, formatId: 654,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "9am",
    feedName: "Maryland-Cash Pop 9am",
    drawDays: "", drawTimeLocal: "09:00 AM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-09",
    mainNumbers: [5],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 09:16:43 AM EDT",
  },
  {
    gameId: 655, formatId: 655,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "1pm",
    feedName: "Maryland-Cash Pop 1pm",
    drawDays: "", drawTimeLocal: "01:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-09",
    mainNumbers: [6],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-10", nextPrizeDisplay: null,
    feedUpdatedRaw: "Thu 07/09/2026 01:16:49 PM EDT",
  },
  {
    gameId: 656, formatId: 656,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "6pm",
    feedName: "Maryland-Cash Pop 6pm",
    drawDays: "", drawTimeLocal: "06:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-08",
    mainNumbers: [15],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 06:16:38 PM EDT",
  },
  {
    gameId: 657, formatId: 657,
    familyKey: "cash-pop", familyName: "Cash Pop",
    gameClass: "frequentDraw", drawPeriod: "11pm",
    feedName: "Maryland-Cash Pop 11pm",
    drawDays: "", drawTimeLocal: "11:00 PM",
    salesCutoff: null, playType: "1/15",
    resultDate: "2026-07-08",
    mainNumbers: [11],
    specialBalls: [],
    multiplier: null,
    secondaryDraw: null,
    topPrizeDisplay: null,
    nextDrawDate: "2026-07-09", nextPrizeDisplay: null,
    feedUpdatedRaw: "Wed 07/08/2026 11:18:04 PM EDT",
  },
];

